//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrolloAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public int IdDocumento { get; set; }
        public int IdTipoDocumento { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime FechaCreación { get; set; }
    }
}
