//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrolloAB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursale
    {
        public int IdSucursales { get; set; }
        public int IdEmpresa { get; set; }
        public string Descripcion { get; set; }
        public string Codigo { get; set; }
        public bool Estado { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public System.DateTime FechaCreación { get; set; }
    
        public virtual Empresa Empresa { get; set; }
    }
}
